language: go
before_script:
  - export QINIU_ACCESS_KEY="iN7NgwM31j4-BZacMjPrOQBs34UG1maYCAQmhdCV"
  - export QINIU_SECRET_KEY="6QTOr2Jg1gcZEWDQXKOGZh5PziC2MCV5KsntT70j"
  - export QINIU_TEST_BUCKET="a"
  - export QINIU_TEST_DOMAIN="aatest.qiniudn.com"
